### ISSUE TITLE
Confusion about the caculation of speech covariance matrix

### ISSUE THREAD

**Issue by vBaiCai** [TJU-haoran/VCTK-16k-simulated#2]
<img width="683" alt="image" src="https://user-images.githubusercontent.com/8043121/202341317-0c6449d5-8654-41a4-b8b9-8ed3f37963b9.png">

Hi haoran,

As described in the paper, Y and S are the complex spectrums of single-channel signals. 

So, the covariance calculated in eq.(3) is actually the **speech energy of the first channel**, normalized by the power of mask ?

Do I understand this right?

**Comment by FYJNEVERFOLLOWS** [comment]
All covariance matrices are computed among all 6 channels, thus getting T * F * C * C matrices containing spatial information among channels. The author made a mistake in the paper. `Y` and `S` denote the 6-channel complex spectrum of mixture and estimated speech, respectively. He was meant to refer to `Mag` as the magnitude of the first channel's mixture spectrum. Sorry for his sloppiness. Thank you for pointing out. 

Our revised version of paper can be found later on arxiv: https://arxiv.org/abs/2207.07307

**Comment by vBaiCai** [comment]
Hi， FYJNEVERFOLLOWS，

Now I can understand.  The C * C spatial covariance is reasonable.  

Thanks for your quick reply!
